import type { FieldNote } from "./types";

export const NOTES: FieldNote[] = [
  {
    date: "2026-09-03",
    scene: "money",
    title: "CoS 走航司客服聊天，把 travel credit 转成刷卡退款",
    source: "@vinit",
    sourceUrl: "https://x.com/vinit/status/2095267295685914781",
    body: "Chief of Staff「Giskard」处理 Frontier 行程。站内没有 cash-refund 按钮，改走官网客服聊天。截图里约 34 分钟后写 $245.58 cash refund is approved。另有 $50 已于 8/31 退卡，还在找 $100 coupon。",
    caution: "金额是作者自述，不是可复制结果。卡号已打码。不可逆退款动作必须走审批。",
  },
  {
    date: "2026-09-03",
    scene: "sales",
    title: "工作日 09:00：排 8 条 live leads，top2 起草外联、不外发",
    source: "@nifinet",
    sourceUrl: "https://x.com/nifinet/status/2095233594407194720",
    body: "工作日 09:00 routine，从 yourmax.ai 排出 8 条 live leads，给 top2 起草外联，不外发。长文写了 PROFILE.md、skills（hunt / rank / outreach）、routines/weekday-signal-digest.md。",
    caution: "文内 MCP 示例是本地 npx stdio。官方 Grok Bot 只支持远程 HTTP MCP。别把 stdio 示例当成官方接法。",
  },
  {
    date: "2026-09-02",
    scene: "money",
    title: "上传信用卡账单，Bot 找订阅并代发退订邮件",
    source: "@mvmeeg",
    sourceUrl: "https://x.com/mvmeeg/status/2095056636872167879",
    body: "把信用卡账单交给 Bot，它找出可退订的订阅，代发退订邮件。作者自称次日有取消确认、省超过 $200/月。",
    caution: "取消套餐前必须逐行点头。金额不可复制。",
  },
  {
    date: "2026-09-02",
    scene: "admin",
    title: "Inbox Manager：过夜分拣，只起草不外发",
    source: "@KanikaBK",
    sourceUrl: "https://x.com/kanikabk/status/2095039599307522106",
    body: "过夜分拣邮箱：SMART TRIAGE（urgent / reply today / later / ignore）→ 起草短回复 → 早起交 5 行简报。NEVER SEND。",
  },
  {
    date: "2026-09-02",
    scene: "admin",
    title: "Inbox → Asana：同线程不重复建任务",
    source: "@wikiwayne",
    sourceUrl: "https://x.com/wikiwayne/status/2095549633351291258",
    body: "邮件分拣进 Asana。明显项自动，需要行动的先问本人或 CoS。同线程、旧主题不建重复任务，只往原任务追加时间线。",
  },
  {
    date: "2026-08",
    scene: "money",
    title: "追回 5 家商家退款，金额超过月费",
    source: "@darian314",
    sourceUrl: "https://x.com/darian314/status/2089381004524093752",
    body: "Bot 在邮件里找没退的货，给 5 家商家写信。作者称追回的钱超过当月 Grok Bot 费用。",
    caution: "外发退款信必须人工审批。到账后再放行下一家。",
  },
  {
    date: "2026-08",
    scene: "money",
    title: "Stripe 客服邮箱接 Bot：常规退款先报备再打钱",
    source: "@GergelyOrosz",
    sourceUrl: "https://x.com/GergelyOrosz/status/2090085668768694562",
    body: "Bot 接到客服邮箱和 Stripe，把常规小额退款做成：先发一条报备，再打钱。既自动化又留痕。",
  },
];
