/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrataRouteImport } from './routes/errata'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ReadSlugRouteImport } from './routes/read.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrataRoute = ErrataRouteImport.update({
  id: '/errata',
  path: '/errata',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadSlugRoute = ReadSlugRouteImport.update({
  id: '/read/$slug',
  path: '/read/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/errata': typeof ErrataRoute
  '/prompts': typeof PromptsRoute
  '/scenes': typeof ScenesRoute
  '/today': typeof TodayRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/errata': typeof ErrataRoute
  '/prompts': typeof PromptsRoute
  '/scenes': typeof ScenesRoute
  '/today': typeof TodayRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/errata': typeof ErrataRoute
  '/prompts': typeof PromptsRoute
  '/scenes': typeof ScenesRoute
  '/today': typeof TodayRoute
  '/read/$slug': typeof ReadSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/errata' | '/prompts' | '/scenes' | '/today' | '/read/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/errata' | '/prompts' | '/scenes' | '/today' | '/read/$slug'
  id:
    | '__root__'
    | '/'
    | '/errata'
    | '/prompts'
    | '/scenes'
    | '/today'
    | '/read/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrataRoute: typeof ErrataRoute
  PromptsRoute: typeof PromptsRoute
  ScenesRoute: typeof ScenesRoute
  TodayRoute: typeof TodayRoute
  ReadSlugRoute: typeof ReadSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errata': {
      id: '/errata'
      path: '/errata'
      fullPath: '/errata'
      preLoaderRoute: typeof ErrataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$slug': {
      id: '/read/$slug'
      path: '/read/$slug'
      fullPath: '/read/$slug'
      preLoaderRoute: typeof ReadSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrataRoute: ErrataRoute,
  PromptsRoute: PromptsRoute,
  ScenesRoute: ScenesRoute,
  TodayRoute: TodayRoute,
  ReadSlugRoute: ReadSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
